# Generated by Django 4.0.1 on 2022-10-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='ru_name',
            field=models.CharField(default='тест', max_length=60),
            preserve_default=False,
        ),
    ]
