# Generated by Django 4.1.1 on 2022-10-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Техническое название категории'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='ru_name',
            field=models.CharField(max_length=60, verbose_name='Название'),
        ),
    ]
