# Generated by Django 4.0.1 on 2022-10-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Food', 'Food'), ('Drinks', 'Drinks')], default='Drinks', max_length=40),
            preserve_default=False,
        ),
    ]
